### ISSUE TITLE
Update breaking functionality

### ISSUE THREAD

**Issue by jakeapp** [magapp/blueiriscmd#1]
script worked great until recent update (perhaps 4.5.3) of blueiris software now it seems to connect but throws off an error:

> Connected to 'Blue Iris Server'
> 200
> {"result":"fail","session"......

any ideas?

**Comment by magapp** [comment]
Yepp, thats true. I've updated, but forgot to commit.

Pull down the latest version and it should work. If not let me know,

**Comment by magapp** [comment]
Just curious, what purpose do you use the script for?

**Comment by jakeapp** [comment]
Works once again!  Great Script..

Using it to automate profiles (and email alerts) based on if car is parked in garage (sets home/away)... 

https://github.com/OpenGarage/OpenGarage-Firmware
built something similar to this only difference is modified firmware working with mqtt and home-assistant to do automation locally
