### ISSUE TITLE
Adding Traffic Signal control

### ISSUE THREAD

**Issue by mikenolet** [magapp/blueiriscmd#2]
I see this information listed in the JSON documents but am unsure on how to implement in the code.  I am looking for the ability to change the signal control with your tool.

status

Get (and optionally set) the state of the traffic signal icon, active global profile as well as the schedule's hold/run state:

signal: a single digit 0 for red, 1 for green, 2 for yellow.

**Comment by magapp** [comment]
I made an update. Just clone the latest and you'll find support for signals and schedules.

Just curious, how do you use signals and schedules?

**Comment by mikenolet** [comment]
I am looking to integrate BI with my home automation platform (Home Assistant) and have the signal trigger to on when everybody is out of the house.  The times may vary so I would leave the schedule always enabled and rely on the trigger to arm/disarm the system.  Thanks a lot for doing the code change.  Is it okay if I reference this in the HomeAssistant fourm?  A few people were asking for this functionality.

**Comment by magapp** [comment]
I do something similar, when arming/disarming my alarm, the profile changes. Depending on profile cameras will record and/or send emails on motion.

Of course you can reference to this.

**Comment by mikenolet** [comment]
I just tested the updated code and it works as expected.  Thanks again.

**Comment by magapp** [comment]
you're welcome
