### ISSUE TITLE
cmd fails when used for Blue Iris 5

### ISSUE THREAD

**Issue by besynnerlig** [magapp/blueiriscmd#5]
Hi there Magnus!

Should the script work for the new Blue Iris version 5?

I've been using your script many years for version 4 without any issues. However I had to reinstall my server and decided to upgrade to version 5. 

`blueiris.py --debug --host MYHOST:81 --user MYUSER --password MYPASS --list-profile`

```
session: 2fe908935b9865ef732828e57a384d02 response: 076990c8401822d7a64b30402ea8a7a4
Connected to 'XXX CCTV'
{u'session': u'2fe908935b9865ef732828e57a384d02', u'result': u'fail'}
Traceback (most recent call last):
  File "/home/ME/blueiriscmd/blueiris.py", line 168, in <module>
    main()
  File "/home/ME/blueiriscmd/blueiris.py", line 29, in main
    print "Profile '%s' is active" % bi.get_profile()
  File "/home/ME/blueiriscmd/blueiris.py", line 142, in get_profile
    profile_id = int(r["profile"])
```

Logging in seems to work since because it echoes "Connected to XXX CCTV'" which is the name of my BI server.

Do you have any idea what's going on?

**Comment by magapp** [comment]
Hi,

Havnt’t had the time to upgrade to 5. When I do, I will avsolutly fix this. I use it myself still.

Planning on upgrade within some months or so

**Comment by besynnerlig** [comment]
I've found the problem and I've submitted PR #6

I believe it will work well also for version 4. Would you like to check that for me?

Thanks!

**Comment by magapp** [comment]
Great! Merged!
